Repository yalesites-org/atomic, pull requests merged in 2022-05, with the labels that each got.

#12 YALB-438: Layout Paragraphs
  .github/workflows/release.yml
  .npmrc
  atomic.info.yml
  atomic.libraries.yml
  package-lock.json
  package.json
  release.config.js
  templates/layouts/ys-layouts--two-column.html.twig
  templates/node/node--full.html.twig
  templates/paragraphs/paragraph--accordion.html.twig
  templates/paragraphs/paragraph--callout.html.twig
  templates/paragraphs/paragraph--cta-banner.html.twig
  templates/paragraphs/paragraph--divider.html.twig
  templates/paragraphs/paragraph--embed.html.twig
  templates/paragraphs/paragraph--pull-quote.html.twig
  templates/paragraphs/paragraph--text-with-image.html.twig
  templates/paragraphs/paragraph--text.html.twig
Labels: needs review

#15 YALB-480: Setup semver on theme repo
  CONTRIBUTING.md
  README.md
Labels: pass code review, ready to merge

#18 YALB-540: Accordion heading
  templates/paragraphs/paragraph--accordion.html.twig
Labels: pass code review, pass functional review, ready to merge
