Repository yalesites-org/atomic, pull requests merged in 2022-09, with the labels that each got.

#35 YALB-237: Add theme settings to twig
  templates/layout/region--footer.html.twig
  templates/layout/region--header.html.twig
Labels: pass code review, pass functional review, ready to merge

#38 YALB-502: Dynamic accordion heading level
  templates/paragraphs/paragraph--accordion-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#36 YALB-293: Wire paragraphs to accept overrides
  templates/paragraphs/paragraph--callout.html.twig
  templates/paragraphs/paragraph--cta-banner.html.twig
  templates/paragraphs/paragraph--pull-quote.html.twig
  templates/paragraphs/paragraph--text-with-image.html.twig
Labels: pass code review, pass functional review

#37 YALB-94 quick links wiring
  .gitignore
  atomic.libraries.yml
  package-lock.json
  templates/field/field--paragraph--field-cards--custom-cards.html.twig
  templates/field/field--paragraph--field-links--quick-links.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
  templates/paragraphs/paragraph--custom-cards.html.twig
  templates/paragraphs/paragraph--quick-links.html.twig
Labels: pass code review, pass functional review, ready to merge

#40 YALB-94: shows subtle variation in drupal
  templates/paragraphs/paragraph--quick-links.html.twig
Labels: pass code review, pass functional review, ready to merge

#44 YALB-718: Fix start time typo
  templates/node/node--event--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#43 YALB-598: Global Settings
  components/_settings/_config.css
  package-lock.json
Labels: pass code review, pass functional review, ready to merge

#39 Release
  .gitignore
  atomic.libraries.yml
  components/_settings/_config.css
  package-lock.json
  templates/field/field--node--created.html.twig
  templates/field/field--paragraph--field-cards--custom-cards.html.twig
  templates/field/field--paragraph--field-links--quick-links.html.twig
  templates/field/field--paragraph--field-tab.html.twig
  templates/layout/page.html.twig
  templates/layout/region--footer.html.twig
  templates/layout/region--header.html.twig
  templates/layouts/ys-layouts--two-column.html.twig
  templates/navigation/menu--main.html.twig
  templates/navigation/menu--utility-navigation.html.twig
  templates/navigation/pager.html.twig
  templates/navigation/ys-breadcrumb-block.html.twig
  templates/node/node--event--card.html.twig
  templates/node/node--event--full.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--full.html.twig
  templates/node/node--news--card.html.twig
  templates/node/node--news--full.html.twig
  templates/node/node--news--list-item.html.twig
  templates/paragraphs/paragraph--accordion-item.html.twig
  templates/paragraphs/paragraph--accordion.html.twig
  templates/paragraphs/paragraph--callout-item.html.twig
  templates/paragraphs/paragraph--callout.html.twig
  templates/paragraphs/paragraph--cta-banner.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
  templates/paragraphs/paragraph--custom-cards.html.twig
  templates/paragraphs/paragraph--divider.html.twig
  templates/paragraphs/paragraph--embed.html.twig
  templates/paragraphs/paragraph--image.html.twig
  templates/paragraphs/paragraph--pop-out-image.html.twig
  templates/paragraphs/paragraph--pull-quote.html.twig
  templates/paragraphs/paragraph--quick-links.html.twig
  templates/paragraphs/paragraph--tab.html.twig
  templates/paragraphs/paragraph--tabs.html.twig
  templates/paragraphs/paragraph--text-with-image.html.twig
  templates/paragraphs/paragraph--text.html.twig
  templates/views/views-view--event-cards.html.twig
  templates/views/views-view--event-list.html.twig
  templates/views/views-view--news-cards.html.twig
  templates/views/views-view--news-list.html.twig
  templates/ys/ys-alert.html.twig
  templates/ys/ys-social-links.html.twig
Labels: don't merge

#45 YALB-742: Update action banner
  atomic.info.yml
  templates/paragraphs/paragraph--cta-banner.html.twig
Labels: pass code review, pass functional review, ready to merge

#47 YALB-713 video wiring
  package-lock.json
  templates/field/field--field-media-oembed-video.html.twig
  templates/paragraphs/paragraph--video.html.twig
Labels: pass code review, pass functional review, ready to merge

#49 YALB-702: Search: Hide search form
  package-lock.json
  templates/field/field--field-media-oembed-video.html.twig
  templates/layout/region--header.html.twig
  templates/paragraphs/paragraph--video.html.twig
Labels: pass functional review, ready to merge

#46 YALB-700: Search Form
  templates/form/form-element-label--search-form.html.twig
  templates/layout/region--header.html.twig
  templates/navigation/menu--utility-navigation.html.twig
Labels: pass code review, pass functional review, ready to merge

#51 YALB-273: Style local tasks
  templates/navigation/menu-local-task.html.twig
  templates/navigation/menu-local-tasks.html.twig
Labels: pass code review, pass functional review
