Repository yalesites-org/atomic, pull requests merged in 2022-11, with the labels that each got.

#56 YALB-784 and YALB-786: Drupal "Primary links" a11y fixes
  templates/navigation/menu-local-tasks.html.twig
Labels: pass code review, pass functional review

#60 YALB-795: Callout edits in Drupal
  templates/paragraphs/paragraph--callout-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#59 YALB-405: Feedback: Breadcrumbs
  templates/node/node--event--full.html.twig
  templates/node/node--full.html.twig
  templates/node/node--news--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#58 YALB-757: all day events
  package-lock.json
  templates/node/node--event--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#62 Release
  package-lock.json
  templates/navigation/menu-local-tasks.html.twig
  templates/node/node--event--full.html.twig
  templates/node/node--full.html.twig
  templates/node/node--news--full.html.twig
  templates/paragraphs/paragraph--callout-item.html.twig
Labels: don't merge

#69 YALB-828: Embeds
  templates/paragraphs/paragraph--embed.html.twig
Labels: pass code review, ready to merge

#70 Release
  .gitignore
  templates/paragraphs/paragraph--embed.html.twig
Labels: pass code review, pass functional review, ready to merge
