Repository yalesites-org/atomic, pull requests merged in 2023-07, with the labels that each got.

#145 YALB-1419 - OPAC: Move admin toolbar to top
  css/admin-theme.css
Labels: pass code review, pass functional review

#148 YALB-1396: Bug: Grand Hero - Pause/play button mobile responsiveness | YALB-1398: Bug: Mega Menu on Tablet | YALB-1405-Bug: Last item drop down in simple menu alignment on center nav | YALB-1287: Confirm fix: Short Banner Height Issue | YALB-1433: Bug: Gallery does not work when on the same page as a media grid
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
Labels: pass code review, pass functional review, ready to merge

#149 YALB-898: Metadata: Add favicon
  templates/layout/html.html.twig
Labels: pass code review, pass functional review

#152 YALB-1394: Bug: Accessibility (FE)- Empty heading being inserted when user does not fill in heading field
  atomic.theme
  templates/block/layout-builder/block--inline-block--gallery.html.twig
  templates/block/layout-builder/block--inline-block--media-grid.html.twig
  templates/block/layout-builder/block--inline-block--video.html.twig
  templates/paragraphs/paragraph--accordion-item.html.twig
  templates/paragraphs/paragraph--gallery-item--gallery-modal-content.html.twig
Labels: pass code review, pass functional review, ready to merge

#155 YALB-1442: WYSIWYG Creating and editing a table is visually and functionally broken
  atomic.libraries.yml
  css/ckeditor-overrides.css
Labels: pass code review, pass functional review, ready to merge

#151 YALB-1407- Bug: Accessibility (FE)- Interactive Media needs roles and tabbing fixes | YALB-1454 - Bug: FE: Quote em dash and name alignment off
  css/layout-builder.css
Labels: pass code review, pass functional review

#153 YALB-1164 - OPAC: Update admin toolbar icons | 1461 - OPAC: Implement new admin colors and fonts
  css/admin-theme.css
  templates/block/layout-builder/block--inline-block--button-link.html.twig
Labels: pass code review, pass functional review

#157 YALB-1388 - Feedback: Embed Block | YALB-1390 - Remove transparency from banner overlay | YALB-1417 - Bug: Block picker in Posts and Events only have 2 columns compared to 3 on Pages | YALB-1463 - Bug: Content Spotlight Border severely impacts use/placement of Block | YALB-858 - Feedback: Site Name looks too small on mobile
  templates/block/layout-builder/block--inline-block--embed.html.twig
Labels: needs review
