Repository yalesites-org/atomic, pull requests merged in 2023-09, with the labels that each got.

#166 YALB 1511 - Theming Primary Navigation Headings
  atomic.libraries.yml
  templates/navigation/menu--extras--main.html.twig
Labels: pass code review, pass functional review

#170 YALB-1552: [admin-theme] Update specific checkbox styles for admin-theme areas
  css/admin-theme.css
Labels: pass code review, pass functional review

#167 fix(yalb-1416): add ternary check for heading value
  templates/block/layout-builder/block--inline-block--cta-banner.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
  templates/block/layout-builder/block--inline-block--view.html.twig
Labels: pass code review, pass functional review

#168 YALB-1057: Add automatic smartquotes
  package-lock.json
  package.json
  templates/block/layout-builder/block--inline-block--custom-cards.html.twig
  templates/block/layout-builder/block--inline-block--directory.html.twig
  templates/block/layout-builder/block--inline-block--event-list.html.twig
  templates/block/layout-builder/block--inline-block--image.html.twig
  templates/block/layout-builder/block--inline-block--post-list.html.twig
  templates/block/layout-builder/block--inline-block--quick-links.html.twig
  templates/block/layout-builder/block--inline-block--wrapped-image.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
Labels: pass code review, pass functional review, ready to merge

#171 YALB-1291: Update to CKEditor5
  atomic.info.yml
  atomic.libraries.yml
  css/admin-theme.css
  css/ckeditor-overrides.css
  css/ckeditor5.css
Labels: needs review

#173 YALB-1057: Bug: Smart quotes issue on heading fields
  templates/block/layout-builder/block--inline-block--custom-cards.html.twig
  templates/block/layout-builder/block--inline-block--directory.html.twig
  templates/block/layout-builder/block--inline-block--event-list.html.twig
  templates/block/layout-builder/block--inline-block--post-list.html.twig
  templates/block/layout-builder/block--inline-block--quick-links.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
Labels: pass code review, pass functional review

#176 fix(YALB-email-copy-change-to-button): add new library
  atomic.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#174 September Release Fixes
  atomic.libraries.yml
  css/admin-theme.css
  css/layout-builder.css
Labels: pass code review, pass functional review, ready to merge
