Repository yalesites-org/atomic, pull requests merged in 2023-03, with the labels that each got.

#96 fix(yalb-995): set width and alignment variables in paragraph templates
  package-lock.json
  templates/node/node--event--full.html.twig
  templates/node/node--news--full.html.twig
  templates/paragraphs/paragraph--accordion.html.twig
  templates/paragraphs/paragraph--image.html.twig
  templates/paragraphs/paragraph--pull-quote.html.twig
  templates/paragraphs/paragraph--tabs.html.twig
  templates/paragraphs/paragraph--text.html.twig
  templates/paragraphs/paragraph--video.html.twig
Labels: needs review

#99 YALB-1018: Bug: Search results shows placeholder
  templates/views/views-view--search.html.twig
Labels: pass code review, pass functional review, ready to merge

#103 YABL-933: Menu: Active trail styles
  atomic.theme
Labels: pass code review, pass functional review, ready to merge

#98 YALB-1011: View Pagination
  templates/field/field--paragraph--field-vb-params.html.twig
  templates/paragraphs/paragraph--basic-view.html.twig
  templates/views/views-view--views-basic-scaffold.html.twig
  templates/views/views-view.html.twig
Labels: needs review, pass code review, pass functional review
