Repository yalesites-org/atomic, pull requests merged in 2023-04, with the labels that each got.

#104 YALB-1051): Fix Accordion spacing
  templates/paragraphs/paragraph--text.html.twig
Labels: pass code review, pass functional review, ready to merge

#102 fix(yalb-alignment) update default widths/alignment
  templates/paragraphs/paragraph--cta-banner.html.twig
  templates/paragraphs/paragraph--custom-cards.html.twig
  templates/paragraphs/paragraph--gallery.html.twig
  templates/paragraphs/paragraph--grand-hero.html.twig
  templates/paragraphs/paragraph--image.html.twig
  templates/paragraphs/paragraph--media-grid.html.twig
  templates/paragraphs/paragraph--pull-quote.html.twig
  templates/paragraphs/paragraph--quick-links.html.twig
  templates/paragraphs/paragraph--tabs.html.twig
  templates/paragraphs/paragraph--webform.html.twig
  templates/paragraphs/paragraph--wrapped-image.html.twig
  templates/views/views-view--event-cards.html.twig
  templates/views/views-view--news-cards.html.twig
  templates/views/views-view--search.html.twig
Labels: pass code review, ready to merge

#95 YALB-1012: Admin Theme: Local Tasks style
  components/_settings/_config.css
Labels: pass code review, pass functional review, ready to merge

#108 fix(yalb-1104): alignment fix - video left align, content/site width …
  templates/paragraphs/paragraph--video.html.twig
Labels: pass code review, ready to merge

#110 fix(yalb-1104): alignment fix - update featured variable from false to true
  templates/views/views-view--event-list.html.twig
  templates/views/views-view--news-list.html.twig
Labels: needs review

#105 YALB-1075: Layout Builder Migration
  package-lock.json
  package.json
  templates/block/layout-builder/_layout-builder-block-template.twig
  templates/block/layout-builder/block--inline-block--accordion.html.twig
  templates/block/layout-builder/block--inline-block--callout.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
  templates/block/layout-builder/block--inline-block--cta-banner.html.twig
  templates/block/layout-builder/block--inline-block--custom-cards.html.twig
  templates/block/layout-builder/block--inline-block--divider.html.twig
  templates/block/layout-builder/block--inline-block--embed.html.twig
  templates/block/layout-builder/block--inline-block--event-list.html.twig
  templates/block/layout-builder/block--inline-block--gallery.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
  templates/block/layout-builder/block--inline-block--image.html.twig
  templates/block/layout-builder/block--inline-block--media-grid.html.twig
  templates/block/layout-builder/block--inline-block--news-list.html.twig
  templates/block/layout-builder/block--inline-block--pull-quote.html.twig
  templates/block/layout-builder/block--inline-block--quick-links.html.twig
  templates/block/layout-builder/block--inline-block--tabs.html.twig
  templates/block/layout-builder/block--inline-block--text.html.twig
  templates/block/layout-builder/block--inline-block--video.html.twig
  templates/block/layout-builder/block--inline-block--view.html.twig
  templates/block/layout-builder/block--inline-block--webform.html.twig
  templates/block/layout-builder/block--inline-block--wrapped-image.html.twig
  templates/block/layout-builder/block--ys-title-breadcrumb-block.html.twig
  templates/block/layout-builder/preview-icons/avatar-icon.svg
  templates/block/layout-builder/preview-icons/banner-icon.svg
  templates/block/layout-builder/preview-icons/rich_text-icon.svg
  templates/field/field--block-content--callout.html.twig
  templates/field/field--block-content--embed.html.twig
  templates/field/field--block-content--field-cards--custom-cards.html.twig
  templates/field/field--block-content--field-links.html.twig
  templates/field/field--block-content--field-media--grand-hero.html.twig
  templates/field/field--block-content--field-media-grid-items--media-grid.html.twig
  templates/field/field--block-content--field-tabs.html.twig
  templates/field/field--block-content--field-view-params.html.twig
  templates/field/field--block-content--pull-quote.html.twig
  templates/field/field--block-content--webform.html.twig
  templates/field/field--paragraph--field-text.html.twig
  templates/node/node--full.html.twig
  templates/paragraphs/_gallery-item.twig
  templates/paragraphs/paragraph--accordion-item.html.twig
  templates/paragraphs/paragraph--accordion.html.twig
  templates/paragraphs/paragraph--callout.html.twig
  templates/paragraphs/paragraph--divider.html.twig
  templates/paragraphs/paragraph--embed.html.twig
  templates/paragraphs/paragraph--event-cards.html.twig
  templates/paragraphs/paragraph--event-list.html.twig
  templates/paragraphs/paragraph--news-cards.html.twig
  templates/paragraphs/paragraph--news-list.html.twig
  templates/paragraphs/paragraph--text-with-image.html.twig
  templates/views/views-view--views-basic-scaffold.html.twig
Labels: pass code review, pass functional review, ready to merge

#114 YALB-1141 - Apply alignment rules to layout builder
  templates/block/layout-builder/block--inline-block--event-list.html.twig
  templates/block/layout-builder/block--inline-block--gallery.html.twig
  templates/block/layout-builder/block--inline-block--image.html.twig
  templates/block/layout-builder/block--inline-block--media-grid.html.twig
  templates/block/layout-builder/block--inline-block--post-list.html.twig
  templates/block/layout-builder/block--inline-block--pull-quote.html.twig
  templates/block/layout-builder/block--inline-block--tabs.html.twig
  templates/block/layout-builder/block--inline-block--text.html.twig
  templates/block/layout-builder/block--inline-block--video.html.twig
  templates/block/layout-builder/block--inline-block--view.html.twig
  templates/block/layout-builder/block--inline-block--wrapped-image.html.twig
Labels: pass code review, pass functional review, ready to merge
