Repository yalesites-org/atomic, pull requests merged in 2023-02, with the labels that each got.

#84 YALB-980: Alignment: Global widths - template updates - wire component library variables
  templates/node/node--event--full.html.twig
  templates/node/node--news--full.html.twig
  templates/paragraphs/paragraph--custom-cards.html.twig
  templates/paragraphs/paragraph--gallery.html.twig
  templates/paragraphs/paragraph--media-grid.html.twig
  templates/paragraphs/paragraph--text.html.twig
  templates/views/views-view--event-cards.html.twig
  templates/views/views-view--news-cards.html.twig
Labels: needs review

#88 Release
  templates/node/node--event--full.html.twig
  templates/node/node--news--full.html.twig
  templates/paragraphs/paragraph--custom-cards.html.twig
  templates/paragraphs/paragraph--gallery.html.twig
  templates/paragraphs/paragraph--media-grid.html.twig
  templates/paragraphs/paragraph--text.html.twig
  templates/views/views-view--event-cards.html.twig
  templates/views/views-view--news-cards.html.twig
Labels: ready to merge

#89 Release
  templates/paragraphs/paragraph--event-cards.html.twig
  templates/paragraphs/paragraph--news-cards.html.twig
Labels: ready to merge

#91 YALB-944: Define template for views basic
  templates/views/views-view--views-basic-scaffold.html.twig
Labels: pass code review, pass functional review, ready to merge

#92 Release
  templates/navigation/menu-local-task.html.twig
  templates/navigation/menu-local-tasks.html.twig
  templates/views/views-view--views-basic-scaffold.html.twig
Labels: pass code review, pass functional review, ready to merge
