Repository yalesites-org/atomic, pull requests merged in 2023-06, with the labels that each got.

#132 YALB-1230: Create Topics vocabulary for Posts
  templates/form/form--views--post-list.html.twig
  templates/views/views-view--post-list.html.twig
Labels: pass code review, pass functional review, ready to merge

#135 YALB-1300: Bug: Error when creating a new event
  package-lock.json
  package.json
  templates/node/node--event--card.html.twig
  templates/node/node--event--full.html.twig
  templates/node/node--event--list-item.html.twig
Labels: needs review

#131 YALB-1197: Media: Allow embed of SoundCloud content (BE)
  templates/ys_embed/broken.html.twig
  templates/ys_embed/embed_wrapper.html.twig
  templates/ys_embed/instagram.html.twig
  templates/ys_embed/powerbi.html.twig
  templates/ys_embed/qualtrics.html.twig
  templates/ys_embed/soundcloud.html.twig
  templates/ys_embed/twitter.html.twig
Labels: needs review, pass code review, pass functional review, ready to merge

#136 YALB-1288: Bug: Search no results message (BE)
  templates/views/views-view--search.html.twig
Labels: pass code review, pass functional review, ready to merge

#137 YALB-1317: Bug: Paragraph duplicate function broken (BE)
  templates/paragraphs/_gallery-item.twig
Labels: pass code review, pass functional review, ready to merge

#139 YALB-1318: Bug: media library - gallery block - multiple photos error
  css/admin-theme.css
Labels: pass code review

#133 YALB-1263 - Layout Builder spacing between components
  atomic.info.yml
  atomic.libraries.yml
  css/layout-builder.css
  templates/block/block--system-messages-block.html.twig
  templates/block/layout-builder/_layout-builder-block-template.twig
  templates/block/status-messages.html.twig
Labels: needs review

#141 YALB-1418: Bug: All events created are showing as past events
  templates/node/node--event--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#142 YALB-1295: Bug: Posts display date of creation and not Publish Date
  atomic.theme
  templates/node/node--post--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#140 YALB-1251 - AX: pencil icon difficulty editing blocks | YALB-1261 - Bug: A11y color issue in rollover menu (FE)
  css/admin-theme.css
Labels: needs review
