Repository yalesites-org/atomic, pull requests merged in 2023-05, with the labels that each got.

#118 YALB-1091 - Style admin forms that appear in atomic
  templates/block/block--system-messages-block.html.twig
  templates/layout/page--403.html.twig
  templates/layout/page--404.html.twig
  templates/views/views-view--frontpage.html.twig
Labels: needs review

#120 YALB-1137: Dividers add new dials to divider block
  templates/block/layout-builder/block--inline-block--divider.html.twig
Labels: pass code review, pass functional review, ready to merge

#121 YALB-395: Metadata: Fallback for teaser images (BE)
  templates/node/node--event--card.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--list-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#123 YALB-1163 - Create Button Link component
  atomic.libraries.yml
  templates/block/layout-builder/block--inline-block--button-link.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
Labels: pass code review, pass functional review

#125 YALB-1205: Webform buttons: add preprocess to pass data-cta-theme attribute
  templates/form/ys-search-form.html.twig
Labels: pass code review, pass functional review

#117 YALB- 988: Override Gin colors and typography
  atomic.libraries.yml
  css/admin-theme.css
Labels: pass code review, pass functional review

#122 YALB-1185 - Atomic Drupal 10 Compatibility
  atomic.info.yml
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
  templates/block/layout-builder/block--inline-block--view.html.twig
Labels: pass code review, pass functional review, ready to merge

#124 YALB-1195: Events: Add to Calendar Link (BE)
  templates/node/node--event--full.html.twig
Labels: pass code review, pass functional review, ready to merge

#126 YALB1145: Levers form: Add icons and custom controls
  css/admin-theme.css
  templates/form/form-element-label--ys-themes-settings-form--button-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--footer-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--global-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--header-theme.html.twig
Labels: pass code review, pass functional review, ready to merge

#129 Release
  css/admin-theme.css
  templates/form/form-element-label--ys-themes-settings-form--button-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--footer-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--global-theme.html.twig
  templates/form/form-element-label--ys-themes-settings-form--header-theme.html.twig
Labels: pass code review, pass functional review, ready to merge

#130 YALB-609: Page lists and grid display modes
  templates/node/node--page--card.html.twig
  templates/node/node--page--list-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#127 YALB-1198: Events: Exposed filters on dynamic list (BE)
  templates/form/form--views--event-list.html.twig
  templates/form/select.html.twig
  templates/form/ys-search-form.html.twig
  templates/views/views-view--event-list.html.twig
  templates/views/views-view--post-list.html.twig
Labels: pass code review, pass functional review
