Repository yalesites-org/atomic, pull requests merged in 2024-09, with the labels that each got.

#257 JAKALA: Spotlight cards enhancement
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
Labels: pass code review, pass functional review

#258 JAKALA: Add Content Type filter to Search Page
  templates/form/ys-search-form.html.twig
  templates/node/node--search-result.html.twig
Labels: needs review, pass code review, pass functional review

#263 YSP-641: Image banner block
  templates/block/layout-builder/block--inline-block--image-banner.html.twig
Labels: needs review, pass functional review

#266 YSP-662: PRESIDENT: allow center or larger view of video block
  templates/block/layout-builder/block--inline-block--video.html.twig
Labels: needs review, pass functional review

#268 YSP-670: Spotlights provide H2 in Banner Section
  css/layout-builder.css
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
Labels: pass functional review
