Repository yalesites-org/atomic, pull requests merged in 2024-04, with the labels that each got.

#216 YSP-422: AX headings aren't adapting to light/dark mode
  css/admin-theme.css
Labels: pass code review, pass functional review, ready to merge

#219 YSP-430: Canvas user need to allow two call to actions in banner
  templates/block/layout-builder/block--inline-block--cta-banner.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
Labels: pass code review, pass functional review

#220 feat(YSP-453): wire media grid to wrap items in li elements
  templates/block/layout-builder/block--inline-block--media-grid.html.twig
  templates/field/field--paragraph--media-grid-item.html.twig
  templates/paragraphs/paragraph--media-grid-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#217 YSP-436: Reference cards: Backend and content tools
  templates/block/layout-builder/block--inline-block--reference-card.html.twig
  templates/field/field--block-content--field-content-ref--reference-card.html.twig
  templates/node/node--event--single.html.twig
  templates/node/node--post--single.html.twig
  templates/node/node--profile--single.html.twig
Labels: pass code review, pass functional review, ready to merge

#223 Release
  css/admin-theme.css
  package-lock.json
  templates/block/layout-builder/block--inline-block--cta-banner.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
  templates/block/layout-builder/block--inline-block--media-grid.html.twig
  templates/block/layout-builder/block--inline-block--reference-card.html.twig
  templates/field/field--block-content--field-content-ref--reference-card.html.twig
  templates/field/field--paragraph--media-grid-item.html.twig
  templates/node/node--event--single.html.twig
  templates/node/node--post--single.html.twig
  templates/node/node--profile--single.html.twig
  templates/paragraphs/paragraph--media-grid-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#222 YSP-399: Localist: Embedding widgets
  atomic.libraries.yml
  css/localist.css
Labels: needs review, pass code review, pass functional review
