Repository yalesites-org/atomic, pull requests merged in 2024-02, with the labels that each got.

#190 YALB-1650 - Reusable Content: Browser UX
  css/layout-builder.css
  templates/block/layout-builder/_layout-builder-block-template.twig
  templates/block/layout-builder/block--broken.html.twig
Labels: needs review

#195 YALB-520: Links: Dynamically apply link treatments
  atomic.libraries.yml
Labels: pass code review, pass functional review

#194 YALB-1681 - Support light and dark admin themes
  css/admin-theme.css
  css/ckeditor5.css
  css/layout-builder.css
Labels: pass code review, pass functional review, ready to merge

#200 YALB-680: Links: Link to external content in lists of cards
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--search-result.html.twig
Labels: pass code review, pass functional review, ready to merge

#205 YSP-354: Release Bug: Edit reusable Block message text color contrast
  css/admin-theme.css
  package-lock.json
  package.json
Labels: pass code review, pass functional review, ready to merge

#201 YALB-1697: Bug: Margin for spotlights
  atomic.libraries.yml
  css/layout-builder.css
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
Labels: pass code review, pass functional review

#202 YSP-277: Spotlight without header shows an empty h tag
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
  templates/block/layout-builder/block--inline-block--custom-cards.html.twig
Labels: needs review

#203 YSP-275: Long email breaks Profile card grid: update wired variables
  templates/node/node--profile--directory.html.twig
Labels: needs review, pass code review, pass functional review, ready to merge
