Repository yalesites-org/atomic, pull requests merged in 2024-06, with the labels that each got.

#224 YSP-458: Editorial Workflow: Display improvements to right panel
  css/admin-theme.css
Labels: needs review

#232 YSP-490, 501, 502, 503, 514: Add Tiles, Facts and Figures, Quote Callout, and Link Grid Blocks
  templates/block/layout-builder/block--inline-block--facts.html.twig
  templates/block/layout-builder/block--inline-block--link-grid.html.twig
  templates/block/layout-builder/block--inline-block--quote-callout.html.twig
  templates/block/layout-builder/block--inline-block--tiles.html.twig
  templates/field/field--block-content--facts.html.twig
  templates/field/field--block-content--field-facts-items.html.twig
  templates/field/field--block-content--field-tiles.html.twig
  templates/field/field--block-content--link-grid.html.twig
  templates/field/field--block-content--quote-callout.html.twig
  templates/field/field--paragraph--link-list.html.twig
  templates/field/field--paragraph--tile.html.twig
  templates/paragraphs/paragraph--facts-item.html.twig
  templates/paragraphs/paragraph--link-list.html.twig
  templates/paragraphs/paragraph--tile.html.twig
Labels: needs review

#235 YSP-560: Localist: Update Event lists + default image updates
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#238 YSP-487: Add JWPlayer Embed
  templates/ys_embed/embed_wrapper.html.twig
Labels: pass functional review, ready to merge

#236 YSP-554 - Hamburger icon shows on empty menu
  templates/layout/region--header.html.twig
Labels: pass code review, pass functional review, ready to merge

#234 YSP-509: Add Code Style to WYSIWYG
  atomic.libraries.yml
  css/ckeditor5.css
  package-lock.json
  package.json
  templates/block/layout-builder/block--inline-block--text.html.twig
Labels: pass code review, pass functional review, ready to merge

#230 Reset main branch when creating releases
  .github/workflows/release.yml
  package.json
Labels: pass code review, ready to merge

#237 YSP-281: Localist Project
  atomic.libraries.yml
  templates/field/field--node--title.html.twig
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--page--card.html.twig
  templates/node/node--page--condensed.html.twig
  templates/node/node--page--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--condensed.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--profile--card.html.twig
  templates/node/node--profile--condensed.html.twig
  templates/node/node--profile--directory.html.twig
  templates/node/node--profile--list-item.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
  templates/views/views-view-unformatted--taxonomy_term--page_1.html.twig
Labels: needs review

#242 feat: bump component-library-twig to 1.43.1
  package-lock.json
  package.json
Labels: needs review

#243 Release
  atomic.libraries.yml
  package-lock.json
  package.json
  templates/field/field--node--title.html.twig
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--page--card.html.twig
  templates/node/node--page--condensed.html.twig
  templates/node/node--page--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--condensed.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--profile--card.html.twig
  templates/node/node--profile--condensed.html.twig
  templates/node/node--profile--directory.html.twig
  templates/node/node--profile--list-item.html.twig
  templates/paragraphs/paragraph--custom-card.html.twig
  templates/views/views-view-unformatted--taxonomy_term--page_1.html.twig
Labels: needs review

#244 fix(semrel): update version to help semrel
  package-lock.json
  package.json
Labels: needs review

#248 feat(v140): bump to latest component library twig
  package-lock.json
Labels: needs review
