Repository yalesites-org/atomic, pull requests merged in 2025-05, with the labels that each got.

#347 IYY-385 :: Table stylign in two columns with a background color
  atomic.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#352 Bump Component Library Twig to v1.56.0
  package-lock.json
Labels: needs review

#353 Release
  atomic.libraries.yml
  atomic.theme
  components/_settings/_config.css
  css/admin-theme.css
  css/layout-builder.css
  package-lock.json
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
  templates/layout/html.html.twig
  templates/navigation/book-tree.html.twig
Labels: needs review

#354 YSP-928: Layout Builder Block Tables in Dark Mode Unreadable
  css/layout-builder.css
Labels: pass code review, pass functional review, ready to merge

#342 IYY-342: All Yale Results powered by Google Programmable Search
  templates/views/_views-view-search.html.twig
Labels: pass code review, pass functional review, ready to merge

#355 Bump Component Library Twig version to 1.57.0
  package-lock.json
Labels: needs review

#356 Release
  css/layout-builder.css
  package-lock.json
  templates/views/_views-view-search.html.twig
Labels: needs review

#358 Hotfix Release
  package-lock.json
Labels: needs review

#361 Hotfix: YSP-951: Breadcrumbs not showing more than 2 trails levels
  templates/navigation/ys-breadcrumb-block.html.twig
Labels: pass code review, pass functional review, ready to merge

#359 Hotfix: YSP-943/YSP-945: Grand Hero and Table fixes
  css/ckeditor5.css
  css/layout-builder.css
Labels: pass code review, pass functional review, ready to merge

#332 YSP-814:: Remove `Show Thumbnails` in reference card to use `with-image`
  templates/node/node--event--card.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--page--card.html.twig
  templates/node/node--page--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--profile--card.html.twig
  templates/node/node--profile--list-item.html.twig
Labels: needs review, pass code review

#363 Bump CL to v1.58.0
  package-lock.json
Labels: needs review

#364 Release
  css/ckeditor5.css
  css/layout-builder.css
  package-lock.json
  templates/navigation/ys-breadcrumb-block.html.twig
  templates/node/node--event--card.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--page--card.html.twig
  templates/node/node--page--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--profile--card.html.twig
  templates/node/node--profile--list-item.html.twig
Labels: needs review
