Repository yalesites-org/atomic, pull requests merged in 2025-02, with the labels that each got.

#298 IYY-271/IYY-300: Views Tool Changes
  templates/node/node--event--card.html.twig
  templates/node/node--event--list-item.html.twig
Labels: needs review, pass code review, pass functional review

#303 IYY-327: Support Video Embed on Image Banner
  templates/block/layout-builder/block--inline-block--video-banner.html.twig
Labels: needs review, pass code review, pass functional review

#301 YSP-769: Add "Pin to Top" visual indicator
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--event--single.html.twig
  templates/node/node--page--card.html.twig
  templates/node/node--page--condensed.html.twig
  templates/node/node--page--list-item.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--condensed.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--post--single.html.twig
  templates/node/node--profile--card.html.twig
  templates/node/node--profile--condensed.html.twig
  templates/node/node--profile--list-item.html.twig
  templates/node/node--profile--single.html.twig
Labels: needs review

#300 IYY-280: Visitors can share Posts | Wiring
  templates/block/block--atomic-addtoanysharebuttons.html.twig
Labels: needs review

#304 IYY-290: Show CAS'd content in Menu Links
  templates/navigation/menu--extras--utility-navigation.html.twig
  templates/navigation/menu--utility-navigation.html.twig
Labels: needs review

#292 IYY-285: Site editors can add a caption to Image Banner | Wiring
  css/layout-builder.css
  templates/block/layout-builder/block--inline-block--image-banner.html.twig
Labels: ready to merge

#313 Update to CL 1.50.0
  package-lock.json
Labels: needs review

#314 Release
  package-lock.json
Labels: needs review

#315 Revert "Take 2..."
  atomic.libraries.yml
  atomic.theme
  templates/block/layout-builder/block--inline-block--divider.html.twig
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
Labels: needs review

#317 Bump CL to 1.51.0
  package-lock.json
Labels: needs review

#312 IYY-281: Visitors can see an estimated read-time on Posts
  atomic.libraries.yml
Labels: needs review, work in progress

#322 Release
  package-lock.json
Labels: needs review

#323 IYY Integration
  atomic.libraries.yml
  css/admin-theme.css
  css/layout-builder.css
  package-lock.json
  templates/block/block--atomic-addtoanysharebuttons.html.twig
  templates/block/layout-builder/block--inline-block--accordion.html.twig
  templates/block/layout-builder/block--inline-block--facts.html.twig
  templates/block/layout-builder/block--inline-block--image-banner.html.twig
  templates/block/layout-builder/block--inline-block--link-grid.html.twig
  templates/block/layout-builder/block--inline-block--tiles.html.twig
  templates/block/layout-builder/block--inline-block--wrapped-text-callout.html.twig
  templates/form/form-element-label--ys-themes-settings-form--book-navigation.html.twig
  templates/layout/region--header.html.twig
  templates/layouts/layout--onecol.html.twig
  templates/navigation/book-tree.html.twig
  templates/navigation/menu--extras--utility-navigation.html.twig
  templates/navigation/menu--utility-navigation.html.twig
  templates/node/node--full.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--condensed.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--post--single.html.twig
  templates/paragraphs/paragraph--tile.html.twig
Labels: needs review

#324 Release
  atomic.libraries.yml
  css/admin-theme.css
  css/layout-builder.css
  package-lock.json
  templates/block/block--atomic-addtoanysharebuttons.html.twig
  templates/block/layout-builder/block--inline-block--accordion.html.twig
  templates/block/layout-builder/block--inline-block--facts.html.twig
  templates/block/layout-builder/block--inline-block--image-banner.html.twig
  templates/block/layout-builder/block--inline-block--link-grid.html.twig
  templates/block/layout-builder/block--inline-block--tiles.html.twig
  templates/block/layout-builder/block--inline-block--wrapped-text-callout.html.twig
  templates/form/form-element-label--ys-themes-settings-form--book-navigation.html.twig
  templates/layout/region--header.html.twig
  templates/layouts/layout--onecol.html.twig
  templates/navigation/book-tree.html.twig
  templates/navigation/menu--extras--utility-navigation.html.twig
  templates/navigation/menu--utility-navigation.html.twig
  templates/node/node--full.html.twig
  templates/node/node--post--card.html.twig
  templates/node/node--post--condensed.html.twig
  templates/node/node--post--list-item.html.twig
  templates/node/node--post--single.html.twig
  templates/paragraphs/paragraph--tile.html.twig
Labels: needs review
