Repository yalesites-org/atomic, pull requests merged in 2025-04, with the labels that each got.

#326 YSP-738 :: Reimplement hiding hamburger menu if no menu items exist
  templates/layout/region--header.html.twig
Labels: pass code review, pass functional review, ready to merge

#327 YSP-844: Event Meta Block Date Visibility Improvements
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--event--single.html.twig
Labels: needs review

#331 YSP-761 :: Add available blocks to regions for new layouts #490
  templates/node/node--post--list-item.html.twig
Labels: pass code review, pass functional review, ready to merge

#334 Bump Component Library to v1.54.0
  package-lock.json
Labels: needs review

#335 Release
  css/layout-builder.css
  package-lock.json
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
  templates/layout/region--header.html.twig
  templates/node/node--event--card.html.twig
  templates/node/node--event--condensed.html.twig
  templates/node/node--event--list-item.html.twig
  templates/node/node--event--single.html.twig
  templates/node/node--post--list-item.html.twig
Labels: needs review

#336 YSP-589: Add Page Content Type Support to Reference Card Block
  templates/node/node--page--single.html.twig
Labels: pass code review, pass functional review, ready to merge

#339 YSP-803: Reduce Excessive Padding Between Breadcrumbs and Banner Blocks
  css/layout-builder.css
Labels: pass functional review, ready to merge

#338 YSP-880: Change default site email from noreply@yale.edu to noreply@noreply.yale.edu
  templates/block/layout-builder/block--inline-block--webform.html.twig
Labels: pass functional review, ready to merge

#343 Bump Component Library Twig to v1.55.0
  package-lock.json
Labels: needs review

#344 Release
  css/layout-builder.css
  package-lock.json
  templates/block/layout-builder/block--inline-block--webform.html.twig
  templates/navigation/ys-breadcrumb-block.html.twig
  templates/node/node--page--single.html.twig
Labels: needs review

#346 YSP-875: Text: Tables in a section have a color contrast issue
  css/layout-builder.css
Labels: pass functional review, ready to merge

#350 ST-Overlay-PNG
  templates/block/layout-builder/block--inline-block--grand-hero.html.twig
Labels: pass code review, pass functional review, ready to merge
