Repository yalesites-org/atomic, pull requests merged in 2025-07, with the labels that each got.

#368 YSP-948 :: Add Caption Field to Spotlight Blocks (Landscape and Portrait)
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
Labels: pass functional review, ready to merge

#366 YSP-568: Improve pagination - too many options
  atomic.theme
  css/admin-theme.css
Labels: pass functional review, ready to merge

#370 YSP-928: Facts and Figures Block - Add Icon Selection Feature
  templates/paragraphs/paragraph--facts-item.html.twig
Labels: pass functional review, ready to merge

#372 Bump CL to 1.59.0
  package-lock.json
Labels: needs review

#373 Release
  atomic.info.yml
  atomic.libraries.yml
  atomic.theme
  css/admin-theme.css
  css/layout-builder.css
  js/disable-menu.js
  package-lock.json
  templates/block/layout-builder/block--inline-block--callout.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight-portrait.html.twig
  templates/block/layout-builder/block--inline-block--content-spotlight.html.twig
  templates/block/layout-builder/block--inline-block--cta-banner.html.twig
  templates/layout/region--header.html.twig
  templates/paragraphs/paragraph--facts-item.html.twig
  templates/views/views-view-unformatted--taxonomy_term--page_1.html.twig
Labels: needs review

#376 Bump component-library-twig to 1.60.0
  package-lock.json
Labels: needs review

#377 Release (RC2)
  package-lock.json
  templates/node/node--view--taxonomy-term.html.twig
  templates/views/views-view-unformatted--taxonomy_term--page_1.html.twig
Labels: needs review

#380 Bump component library twig to 1.61.0
  package-lock.json
Labels: ready to merge

#381 Release (RC3)
  package-lock.json
  templates/block/layout-builder/block--inline-block--inline-message.html.twig
Labels: ready to merge

#384 Release (RC4)
  css/admin-theme.css
  package-lock.json
Labels: ready to merge
